//---------------------------------------------------------------------------
// This code was generated by a tool. Changes to this file may cause 
// incorrect behavior and will be lost if the code is regenerated.
//
// WCF Architect Version:	2.0.0.12504
// .NET Framework Version:	4.5
//---------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Net;
using System.Net.Security;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Runtime.Serialization;
using System.ServiceModel;
using System.ServiceModel.Description;
using System.Text;

#pragma warning disable 1591
namespace WCFArchitect.SampleServer.BasicNET
{
	/**************************************************************************
	*	Service Contracts
	**************************************************************************/

<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
	[System.CodeDom.Compiler.GeneratedCodeAttribute("WCF Architect .NET CSharp Generator - BETA", "2.0.2000.0")]
	[ServiceContract(SessionMode = System.ServiceModel.SessionMode.Allowed, Namespace = "http://tempuri.org/WCFArchitect/SampleServer/BasicNET/")]
=======
	[System.CodeDom.Compiler.GeneratedCodeAttribute("WCF Architect .NET CSharp Generator - BETA", "2.0.0.12501")]
=======
	[System.CodeDom.Compiler.GeneratedCodeAttribute("WCF Architect .NET CSharp Generator - BETA", "2.0.0.12504")]
>>>>>>> 6696ce9... WA-78 Rewrote Endpoint generation code to support Protocol Buffer Serialization.
	[ServiceContract(CallbackContract = typeof(ITestNETCallback), SessionMode = System.ServiceModel.SessionMode.Allowed, Namespace = "http://tempuri.org/WCFArchitect/SampleServer/BasicNET/")]
>>>>>>> fefd949... Refixed WA-112
=======
	[System.CodeDom.Compiler.GeneratedCodeAttribute("WCF Architect .NET CSharp Generator - BETA", "2.0.0.12504")]
	[ServiceContract(CallbackContract = typeof(ITestNETCallback), SessionMode = System.ServiceModel.SessionMode.Allowed, Namespace = "http://tempuri.org/WCFArchitect/SampleServer/BasicNET/")]
>>>>>>> origin/master
	public interface ITestNET
	{
		[OperationContract(ProtectionLevel = System.Net.Security.ProtectionLevel.None)]
		WCFArchitect.SampleServer.BasicWinRT.Customer RefTestAsync();

	}
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
=======
	[System.CodeDom.Compiler.GeneratedCodeAttribute("WCF Architect .NET CSharp Generator - BETA", "2.0.0.12501")]
=======
	[System.CodeDom.Compiler.GeneratedCodeAttribute("WCF Architect .NET CSharp Generator - BETA", "2.0.0.12504")]
>>>>>>> 6696ce9... WA-78 Rewrote Endpoint generation code to support Protocol Buffer Serialization.
=======
	[System.CodeDom.Compiler.GeneratedCodeAttribute("WCF Architect .NET CSharp Generator - BETA", "2.0.0.12504")]
>>>>>>> origin/master
	public interface ITestNETCallback
	{
		[OperationContract(ProtectionLevel = System.Net.Security.ProtectionLevel.None)]
		WCFArchitect.SampleServer.BasicWinRT.Customer RetTestCallbackAsync();

	}
	[System.CodeDom.Compiler.GeneratedCodeAttribute("WCF Architect .NET CSharp Generator - BETA", "2.0.0.12504")]
	public partial class TestNETCallback : ITestNETCallback
	{

		private readonly ITestNETCallback __callback;

		public TestNETCallback()
		{
			__callback = System.ServiceModel.OperationContext.Current.GetCallbackChannel<ITestNETCallback>();
		}

		public TestNETCallback(ITestNETCallback callback)
		{
			__callback = callback;
		}

		public WCFArchitect.SampleServer.BasicWinRT.Customer RetTestCallbackAsync()
		{
			return __callback.RetTestCallbackAsync();
		}

	}
<<<<<<< HEAD
>>>>>>> fefd949... Refixed WA-112
=======
>>>>>>> origin/master


}

#pragma warning restore 1591
