//---------------------------------------------------------------------------
// This code was generated by a tool. Changes to this file may cause 
// incorrect behavior and will be lost if the code is regenerated.
//
// WCF Architect Version:	2.0.2000.0
// .NET Framework Version:	4.5
//---------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Net;
using System.Net.Security;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Runtime.Serialization;
using System.ServiceModel;
using System.ServiceModel.Description;
using System.Text;

#pragma warning disable 1591
namespace WCFArchitect.SampleServer.BasicWinRT
{
	/**************************************************************************
	*	Enumerations
	**************************************************************************/

	[System.CodeDom.Compiler.GeneratedCodeAttribute("WCF Architect .NET CSharp Generator - BETA", "2.0.2000.0")]
	[DataContract(Namespace = "http://tempuri.org/WCFArchitect/SampleServer/BasicWinRT/")]
	public enum Colors : long
	{
		[EnumMember()] Blue,
		[EnumMember()] Green,
		[EnumMember()] Red,
		[EnumMember()] Yellow,
		[EnumMember()] Orange,
		[EnumMember()] Gray,
		[EnumMember()] Teal,
		[EnumMember()] Black,
	}


	/**************************************************************************
	*	Data Contracts
	**************************************************************************/

	[System.CodeDom.Compiler.GeneratedCodeAttribute("WCF Architect .NET CSharp Generator - BETA", "2.0.2000.0")]
	[DataContract(Name = "Customer", Namespace = "http://tempuri.org/WCFArchitect/SampleServer/BasicWinRT/")]
	public partial class Customer
	{
		[DataMember(Name = "ID")] public Guid ID { get; set; }
		[DataMember(Name = "Name")] public string Name { get; set; }
		[DataMember(Name = "AddressLine1")] public string AddressLine1 { get; set; }
		[DataMember(Name = "AddressLine2")] public string AddressLine2 { get; set; }
		[DataMember(Name = "City")] public string City { get; set; }
		[DataMember(Name = "State")] public string State { get; set; }
		[DataMember(Name = "ZipCode")] public int ZipCode { get; set; }
		[DataMember(Name = "Color")] public WCFArchitect.SampleServer.BasicWinRT.Colors Color { get; set; }
	}


	/**************************************************************************
	*	Service Contracts
	**************************************************************************/

	[System.CodeDom.Compiler.GeneratedCodeAttribute("WCF Architect .NET CSharp Generator - BETA", "2.0.2000.0")]
	[ServiceContract(SessionMode = System.ServiceModel.SessionMode.Required, Namespace = "http://tempuri.org/WCFArchitect/SampleServer/BasicWinRT/")]
	public interface ICustomers
	{
		WCFArchitect.SampleServer.BasicWinRT.Customer LastCustomer { [OperationContract(Name = "GetLastCustomer")] get;  }

		///<param name='NewCustomer'></param>
		[OperationContract(IsInitiating = false, IsOneWay = true)]
		void AddCustomerAsync(WCFArchitect.SampleServer.BasicWinRT.Customer NewCustomer);

		[OperationContract(IsInitiating = false)]
		WCFArchitect.SampleServer.BasicWinRT.Customer GetCustomerAsync();

		///<param name='Updated'></param>
		[OperationContract(IsInitiating = false, IsOneWay = true)]
		void UpdateCustomerAsync(WCFArchitect.SampleServer.BasicWinRT.Customer Updated);

		///<param name='CustomerID'></param>
		[OperationContract(IsInitiating = false)]
		bool DeleteCustomer(Guid CustomerID);

	}


	/**************************************************************************
	*	Service Bindings
	**************************************************************************/

	[System.CodeDom.Compiler.GeneratedCodeAttribute("WCF Architect .NET CSharp Generator - BETA", "2.0.2000.0")]
	public partial class CustomerNetHttpBinding : System.ServiceModel.NetHttpBinding
	{
		public CustomerNetHttpBinding()
		{
			SetDefaults();
		}
		public CustomerNetHttpBinding(System.ServiceModel.BasicHttpSecurity CustomSecurity)
		{
			SetDefaults();
			this.Security = CustomSecurity;
		}
		public CustomerNetHttpBinding(System.Xml.XmlDictionaryReaderQuotas ReaderQuotas)
		{
			SetDefaults();
			this.ReaderQuotas = ReaderQuotas;
		}
		public CustomerNetHttpBinding(System.ServiceModel.BasicHttpSecurity CustomSecurity, System.Xml.XmlDictionaryReaderQuotas ReaderQuotas)
		{
			SetDefaults();
			this.Security = CustomSecurity;
			this.ReaderQuotas = ReaderQuotas;
		}
		private void SetDefaults()
		{
			this.Name = "CustomerNetHttpBinding";
			this.Namespace = "http://tempuri.org";
			this.OpenTimeout = new TimeSpan(600000000);
			this.CloseTimeout = new TimeSpan(600000000);
			this.SendTimeout = new TimeSpan(600000000);
			this.ReceiveTimeout = new TimeSpan(6000000000);
			this.AllowCookies = false;
			this.MaxBufferPoolSize = 524288;
			this.MaxBufferSize = 65536;
			this.MaxReceivedMessageSize = 65536;
			this.MessageEncoding = NetHttpMessageEncoding.Text;
			this.TextEncoding = System.Text.Encoding.UTF8;
			this.TransferMode = TransferMode.Buffered;
			this.WebSocketSettings.DisablePayloadMasking = false;
			this.WebSocketSettings.KeepAliveInterval = new TimeSpan(6000000000);
			this.WebSocketSettings.SubProtocol = "";
			this.WebSocketSettings.TransportUsage = System.ServiceModel.Channels.WebSocketTransportUsage.WhenDuplex;
			this.HostNameComparisonMode = HostNameComparisonMode.StrongWildcard;
			this.WebSocketSettings.CreateNotificationOnConnection = false;
			this.WebSocketSettings.MaxPendingConnections = 32;
			this.ReliableSession.Enabled = true;
			this.ReliableSession.InactivityTimeout = new TimeSpan(6000000000);
			this.ReliableSession.Ordered = true;
			this.BypassProxyOnLocal = false;
			this.Security.Mode = BasicHttpSecurityMode.None;
			this.Security.Transport.ClientCredentialType = HttpClientCredentialType.None;
			this.Security.Transport.ProxyCredentialType = HttpProxyCredentialType.None;
			this.Security.Transport.Realm = "";
			this.Security.Message.AlgorithmSuite = System.ServiceModel.Security.SecurityAlgorithmSuite.Basic256;
			this.Security.Message.ClientCredentialType = BasicHttpMessageCredentialType.UserName;

		}
	}


	/**************************************************************************
	*	Service Hosts
	**************************************************************************/

	[System.CodeDom.Compiler.GeneratedCodeAttribute("WCF Architect .NET CSharp Generator - BETA", "2.0.2000.0")]
	public partial class CustomerHost : ServiceHost
	{
		public static Uri NetHttpEndpointURI { get { return new Uri("http://" + Environment.MachineName + "/NetHttpEndpoint"); } }
		public ServiceThrottlingBehavior NetHttpThrottlingBehavior { get; private set; }
		public CustomerHost(object singletonInstance) : base(singletonInstance)
		{
			this.Authorization.ImpersonateCallerForAllOperations = false;
			this.Authorization.PrincipalPermissionMode = System.ServiceModel.Description.PrincipalPermissionMode.None;
			this.CloseTimeout = new TimeSpan(600000000);
			this.OpenTimeout = new TimeSpan(600000000);
			this.Description.Name = "CustomerHost";
			this.Description.Namespace = "http://tempuri.org/";
			this.NetHttpThrottlingBehavior = new ServiceThrottlingBehavior();
			this.NetHttpThrottlingBehavior.MaxConcurrentCalls = 16;
			this.NetHttpThrottlingBehavior.MaxConcurrentInstances = 26;
			this.NetHttpThrottlingBehavior.MaxConcurrentSessions = 10;
			this.AddServiceEndpoint(typeof(WCFArchitect.SampleServer.BasicWinRT.ICustomers), new WCFArchitect.SampleServer.BasicWinRT.CustomerNetHttpBinding(), NetHttpEndpointURI);
		}
		public CustomerHost(Type serviceType) : base(serviceType)
		{
			this.Authorization.ImpersonateCallerForAllOperations = false;
			this.Authorization.PrincipalPermissionMode = System.ServiceModel.Description.PrincipalPermissionMode.None;
			this.CloseTimeout = new TimeSpan(600000000);
			this.OpenTimeout = new TimeSpan(600000000);
			this.Description.Name = "CustomerHost";
			this.Description.Namespace = "http://tempuri.org/";
			this.NetHttpThrottlingBehavior = new ServiceThrottlingBehavior();
			this.NetHttpThrottlingBehavior.MaxConcurrentCalls = 16;
			this.NetHttpThrottlingBehavior.MaxConcurrentInstances = 26;
			this.NetHttpThrottlingBehavior.MaxConcurrentSessions = 10;
			this.AddServiceEndpoint(typeof(WCFArchitect.SampleServer.BasicWinRT.ICustomers), new WCFArchitect.SampleServer.BasicWinRT.CustomerNetHttpBinding(), NetHttpEndpointURI);
		}
		public CustomerHost(object singletonInstance, params Uri[] BaseAddresses) : base(singletonInstance, BaseAddresses)
		{
			this.Authorization.ImpersonateCallerForAllOperations = false;
			this.Authorization.PrincipalPermissionMode = System.ServiceModel.Description.PrincipalPermissionMode.None;
			this.CloseTimeout = new TimeSpan(600000000);
			this.OpenTimeout = new TimeSpan(600000000);
			this.Description.Name = "CustomerHost";
			this.Description.Namespace = "http://tempuri.org/";
			this.NetHttpThrottlingBehavior = new ServiceThrottlingBehavior();
			this.NetHttpThrottlingBehavior.MaxConcurrentCalls = 16;
			this.NetHttpThrottlingBehavior.MaxConcurrentInstances = 26;
			this.NetHttpThrottlingBehavior.MaxConcurrentSessions = 10;
			this.AddServiceEndpoint(typeof(WCFArchitect.SampleServer.BasicWinRT.ICustomers), new WCFArchitect.SampleServer.BasicWinRT.CustomerNetHttpBinding(), NetHttpEndpointURI);
		}
		public CustomerHost(Type serviceType, params Uri[] BaseAddresses) : base(serviceType, BaseAddresses)
		{
			this.Authorization.ImpersonateCallerForAllOperations = false;
			this.Authorization.PrincipalPermissionMode = System.ServiceModel.Description.PrincipalPermissionMode.None;
			this.CloseTimeout = new TimeSpan(600000000);
			this.OpenTimeout = new TimeSpan(600000000);
			this.Description.Name = "CustomerHost";
			this.Description.Namespace = "http://tempuri.org/";
			this.NetHttpThrottlingBehavior = new ServiceThrottlingBehavior();
			this.NetHttpThrottlingBehavior.MaxConcurrentCalls = 16;
			this.NetHttpThrottlingBehavior.MaxConcurrentInstances = 26;
			this.NetHttpThrottlingBehavior.MaxConcurrentSessions = 10;
			this.AddServiceEndpoint(typeof(WCFArchitect.SampleServer.BasicWinRT.ICustomers), new WCFArchitect.SampleServer.BasicWinRT.CustomerNetHttpBinding(), NetHttpEndpointURI);
		}
		public CustomerHost(object singletonInstance, bool DisableDefaultEndpoints) : base(singletonInstance)
		{
			this.Authorization.ImpersonateCallerForAllOperations = false;
			this.Authorization.PrincipalPermissionMode = System.ServiceModel.Description.PrincipalPermissionMode.None;
			this.CloseTimeout = new TimeSpan(600000000);
			this.OpenTimeout = new TimeSpan(600000000);
			this.Description.Name = "CustomerHost";
			this.Description.Namespace = "http://tempuri.org/";
			this.NetHttpThrottlingBehavior = new ServiceThrottlingBehavior();
			this.NetHttpThrottlingBehavior.MaxConcurrentCalls = 16;
			this.NetHttpThrottlingBehavior.MaxConcurrentInstances = 26;
			this.NetHttpThrottlingBehavior.MaxConcurrentSessions = 10;
			if(DisableDefaultEndpoints == false)
			{
			this.AddServiceEndpoint(typeof(WCFArchitect.SampleServer.BasicWinRT.ICustomers), new WCFArchitect.SampleServer.BasicWinRT.CustomerNetHttpBinding(), NetHttpEndpointURI);
			}
		}
		public CustomerHost(Type serviceType, bool DisableDefaultEndpoints) : base(serviceType)
		{
			this.Authorization.ImpersonateCallerForAllOperations = false;
			this.Authorization.PrincipalPermissionMode = System.ServiceModel.Description.PrincipalPermissionMode.None;
			this.CloseTimeout = new TimeSpan(600000000);
			this.OpenTimeout = new TimeSpan(600000000);
			this.Description.Name = "CustomerHost";
			this.Description.Namespace = "http://tempuri.org/";
			this.NetHttpThrottlingBehavior = new ServiceThrottlingBehavior();
			this.NetHttpThrottlingBehavior.MaxConcurrentCalls = 16;
			this.NetHttpThrottlingBehavior.MaxConcurrentInstances = 26;
			this.NetHttpThrottlingBehavior.MaxConcurrentSessions = 10;
			if(DisableDefaultEndpoints == false)
			{
			this.AddServiceEndpoint(typeof(WCFArchitect.SampleServer.BasicWinRT.ICustomers), new WCFArchitect.SampleServer.BasicWinRT.CustomerNetHttpBinding(), NetHttpEndpointURI);
			}
		}
		public CustomerHost(object singletonInstance, bool DisableDefaultEndpoints, params Uri[] BaseAddresses) : base(singletonInstance, BaseAddresses)
		{
			this.Authorization.ImpersonateCallerForAllOperations = false;
			this.Authorization.PrincipalPermissionMode = System.ServiceModel.Description.PrincipalPermissionMode.None;
			this.CloseTimeout = new TimeSpan(600000000);
			this.OpenTimeout = new TimeSpan(600000000);
			this.Description.Name = "CustomerHost";
			this.Description.Namespace = "http://tempuri.org/";
			this.NetHttpThrottlingBehavior = new ServiceThrottlingBehavior();
			this.NetHttpThrottlingBehavior.MaxConcurrentCalls = 16;
			this.NetHttpThrottlingBehavior.MaxConcurrentInstances = 26;
			this.NetHttpThrottlingBehavior.MaxConcurrentSessions = 10;
			if(DisableDefaultEndpoints == false)
			{
			this.AddServiceEndpoint(typeof(WCFArchitect.SampleServer.BasicWinRT.ICustomers), new WCFArchitect.SampleServer.BasicWinRT.CustomerNetHttpBinding(), NetHttpEndpointURI);
			}
		}
		public CustomerHost(Type serviceType, bool DisableDefaultEndpoints, params Uri[] BaseAddresses) : base(serviceType, BaseAddresses)
		{
			this.Authorization.ImpersonateCallerForAllOperations = false;
			this.Authorization.PrincipalPermissionMode = System.ServiceModel.Description.PrincipalPermissionMode.None;
			this.CloseTimeout = new TimeSpan(600000000);
			this.OpenTimeout = new TimeSpan(600000000);
			this.Description.Name = "CustomerHost";
			this.Description.Namespace = "http://tempuri.org/";
			this.NetHttpThrottlingBehavior = new ServiceThrottlingBehavior();
			this.NetHttpThrottlingBehavior.MaxConcurrentCalls = 16;
			this.NetHttpThrottlingBehavior.MaxConcurrentInstances = 26;
			this.NetHttpThrottlingBehavior.MaxConcurrentSessions = 10;
			if(DisableDefaultEndpoints == false)
			{
			this.AddServiceEndpoint(typeof(WCFArchitect.SampleServer.BasicWinRT.ICustomers), new WCFArchitect.SampleServer.BasicWinRT.CustomerNetHttpBinding(), NetHttpEndpointURI);
			}
		}
	}


}

#pragma warning restore 1591
