using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace WCFArchitect.Samples.HelloWCF
{
	class Program
	{
		static void Main(string[] args)
		{
			Console.WriteLine("WCF Architect Sample Server");
			Console.WriteLine("Press Escape to terminate.");
			Console.WriteLine();
			Console.Write("Starting the Service Host ... ");

			//Set-up the service host using the code generated by WCF Architect.
			Hosts.PipeHost ServerHost = new Hosts.PipeHost(typeof(Users), true);
			ServerHost.AddServiceEndpoint(typeof(IUsers), new Bindings.NamedPipeBinding(), Hosts.PipeHost.PipeEndpointURI);
			ServerHost.Open();		//Open the server

			Console.WriteLine("Service Started!");

			while (Console.ReadKey().Key != ConsoleKey.Escape)
			{ }

			ServerHost.Close();		//Close the server

			Console.WriteLine("Service Stopped!");
		}
	}
}